### ISSUE TITLE
user-level interaction with multiple sets (matrix)

### ISSUE THREAD

**Issue by paxperscientiam** [marekdedic/imagelightbox#101]
What do you think, @rejas, of allowing for the creation of a 2D imageLightbox? Basically, there is some trigger to open two or more imageLightbox sets. While the 'left' and 'right' actions will continue to work as they do now, 'up' and 'down' actions would switch user-level interaction to another imageLightbox.

This basically piggybacks off of #92 
EDIT: Also piggy backs off of #91

**Comment by rejas** [comment]
very interesting idea if it can be done without too much growth size :-)

**Comment by marekdedic** [comment]
Hi, I'm cleaning up old issues. This seems to me to be way too complicated and confusing for users. I'm closing this until there is a reasonable proposal with some mockups on how to do this with good UX.
