### ISSUE TITLE
Auto document?

### ISSUE THREAD

**Issue by paxperscientiam** [marekdedic/imagelightbox#106]
I think it would be a good idea to programmatically generate documentation from the comments.

**Comment by rejas** [comment]
like in javadoc?

**Comment by paxperscientiam** [comment]
Yeah

**Comment by rejas** [comment]
I see the value for the options and events but to be honest, I havent looked at any js-doc at all in my career :-) any recommmendations/ideas?

**Comment by marekdedic** [comment]
Isn't this mostly obsoleted by the fact that we expose TypeScript typings now?
