### ISSUE TITLE
Use CSS to hide links that don't wrap images

### ISSUE THREAD

**Issue by paxperscientiam** [marekdedic/imagelightbox#107]
It seems that sometimes the default display property for anchor elements can clash with flex stuff. I haven't quite nailed down the specifics. That said, setting anchor elements without dependents to `display:none` seems like the safer bet.

I will do this.

**Comment by marekdedic** [comment]
I think we aren't relying on `display: none` for anything other than the caption. Please re-open if I'm wrong.
