### ISSUE TITLE
Flash an indicator for fullscreen

### ISSUE THREAD

**Issue by paxperscientiam** [marekdedic/imagelightbox#129]
When fullscreen is possible, a message should flash or otherwise indicate to user that the `enter` key will toggle fullscreen mode.

**Comment by rejas** [comment]
Good point @GenaBitu. Also, most browsers already show some message when fullscreen is triggered. So I am closing this issue.

**Comment by GenaBitu** [comment]
Oh, I don't think it was meant as a message when fullscreen is triggered - I think it was meant as a message kind of like "You can press Enter to enter fullscreen" when the lightbox is opened, because otherwise most user won't know about the option to do so.

**Comment by rejas** [comment]
Aaaah, correct... Maybe an icon would suffice? But where to put it?

**Comment by GenaBitu** [comment]
Oh, I don't know about an icon, but maybe it could work if done well. I was kind of imagining something like a floating caption in the bottom right corner that disappears after `n` seconds...

**Comment by rejas** [comment]
Right now I have other projects to focus on so I leave this issue open but wont do it myself.
If somebody comes up with a good mockup, I'd reconsider this (dont do a PR before a design/idea is formulated). But normally your page should show this hint and not the library.

**Comment by paxperscientiam** [comment]
I'm on the, but IIRC there is a pretty widely accepted icon for indicating
fullscreen

**Comment by GenaBitu** [comment]
http://fontello.com/#search=fullscreen
Maybe in combination with
https://www.iconfinder.com/icons/2961578/computer_device_enter_key_keyboard_return_icon#size=256

**Comment by rejas** [comment]
Well, there are icons for fullscreen indeed but those are for clicking on it, not for signalling "hey, press enter to go fullscreen" 
And showing two icons sidebyside (icon_fullscreen)(icon_enter_key) seems convoluted to me....

**Comment by GenaBitu** [comment]
Ok, why not go the simple route and instead of a fullscreen hint add a fullscreen button?

**Comment by rejas** [comment]
Where would you put it in attached image? 
![screenshot-2018-6-14 imagelightbox](https://user-images.githubusercontent.com/1313547/41407422-a7d1ed24-6fcf-11e8-969f-760ea862b0e3.png)

**Comment by GenaBitu** [comment]
My idea would be either in the bottom right of the image or in the bottom right of the screen. (Thats purely subjective though...) Also I think the idea of the button disappearing after some timeout might also make sense here (especially if the button would be over the image...)
