### ISSUE TITLE
Magnification

### ISSUE THREAD

**Issue by paxperscientiam** [marekdedic/imagelightbox#162]
What?
Add option to override image's dimensions.

Why?
Avoid needing excess CSS when using 1px placeholder images.

Since I did a lot of the weird relative dimension stuff re gutters and what not, I'll take care of this one!

**Comment by rejas** [comment]
Happy for any PR. Is there an example for this placeholder use case?

**Comment by paxperscientiam** [comment]
Use case is prototyping without http requests: 1 px image using a data-uri, scaled to desired dimensions.

Maybe, it should just be a "prototyping" feature or something? Yeah, PR coming!

**Comment by marekdedic** [comment]
Hi, I'm cleaning up old issues. You can use pinch to zoom now, but I'm not 100% sure that's what this issue is about. If it's about something more involved, could you please give a further description?
