### ISSUE TITLE
Recognize gallery namespaces implicitly (zero (JS) config)

### ISSUE THREAD

**Issue by paxperscientiam** [marekdedic/imagelightbox#171]
Feature request: add option to automatically create lightbox gallery (or galleries) from elements when attribute `data-imagelightbox` is non-zero/non-null, making as many lightbox galleries as there are unique `data-imagelightbox` values.

**Comment by marekdedic** [comment]
I honestly think it would be cool to be able to create many lightbox instances at once. However, I currently see no way to do this as the API is now more class-like where the lightbox instance is used for interactions such as adding images.

So I'm closing this for now unless we can come up with a way to do this consistenly with the current API.
