### ISSUE TITLE
Scrolling just fast enough breaks the order of images.

### ISSUE THREAD

**Issue by marekdedic** [marekdedic/imagelightbox#176]
Best seen with the navigation on:

I was trying the navigation example from the docs and if i "scroll" twice in a succession, the navigation moves by 2 images, but the actual image only by 1 - so the navigation becomes out of sync with the actual image.

When I scroll further, it turns out that the navigation is taken as the "ground truth", not the actual image - so you can miss an image if you are just scrolling through...

To replicate: Open the docs, open the navigation example. "Scroll" right (I am using arrows). When the image is sliding into the position, scroll for a second time. You should now see the navigation on the third image, but you only see the second image. When you scroll further, it's as if you were on the third image.
Might have to try multiple times to replicate, it's kind of finicky...

**Comment by GenaBitu** [comment]
Oh, and this happens on `develop`, so I didn't cause this with #174 :) (I originally thought I might have)

**Comment by GenaBitu** [comment]
Ok, some preliminary notes:

The `loaded` event never fires for the "skipped" image. Obviously some kind of race condition

**Comment by rejas** [comment]
Grmpfl, the "best" kind of issues :-(

**Comment by GenaBitu** [comment]
Ok, I've removed the line...

Now the event on line 520 (f6d3c13) never fires, so the third image is never displayed.

**Comment by GenaBitu** [comment]
Ok, I'm seeing 2 phenomena:
Either the event on line 520 never fires, or
line 492 doesn't append the image to the wrapper.

(Both line numbers in commit f6d3c13).

For either, I have no idea why.

**Comment by rejas** [comment]
So probably nothing we can fix easily ?

**Comment by paxperscientiam** [comment]
@marekdedic any chance to demonstrate this on video/gif?

**Comment by marekdedic** [comment]
https://send.firefox.com/download/875d90a82aba36b9/#Zi6jF8A64vFALZUaFS41ow

I was pressing the right arrow twice (once on the first image and a second time just as the second image was arriving). The after a while I pressed left once. Pay attention to the navigation on the bottom.
