### ISSUE TITLE
Transfer ownership

### ISSUE THREAD

**Issue by rejas** [marekdedic/imagelightbox#199]
hey @marekdedic 
I am about to release v1.0.0 with the current master branch as is.
Given the facts that I am not actively using this library anymore and that in the foreseeable future I will have to consolidate my dev activities I am thinking of handing maintainership of this library over to you. That would also include npm publishing rights.
Would you be willing to take this over?

**Comment by marekdedic** [comment]
Hi,
I'm sorry to hear that you no longer have the time for the project - although I understand...

I would gladly take over for the time being. I hope other contributors (of which I know only of @paxperscientiam) would be willing to continue to contribute.

Thanks,
Marek

**Comment by rejas** [comment]
Initialised transfer. Now I'd need your npm handle :-)

**Comment by marekdedic** [comment]
The same as here, `marekdedic` :) (I just created it...)

**Comment by rejas** [comment]
Done :-) Thx for taking over!

**Comment by paxperscientiam** [comment]
@rejas , you've been such a good steward of this project. IDK if original author ever gave his opinion of this fork, but it's been a joy to contribute. ILB has matured a lot.
@marekdedic , I wish I could say for sure, but I hope to contribute more!

@rejas , could luck with your endeavors 👍

**Comment by marekdedic** [comment]
I can confirm I have the repo and the NPM package under my account now.

@rejas Thanks for making this package and making it easier to use (the original was rather bare-bones). You're still welcome to occasionally pop in with an opinion or a PR, depending on your time... Good luck!@paxperscientiam I think the pace is rather slow, but I don't necessarily think that's a bad thing...

**Comment by rejas** [comment]
Thx you two for helping me with the library. Of course I will still stick around and watch this repo ;-)
