### ISSUE TITLE
Cant close Lightbox

### ISSUE THREAD

**Issue by MarioBuehne** [marekdedic/imagelightbox#212]
So i have lightbox added to my page but everytime i click on an image i cant close it.
The only things i changed in the lightbox.js file is that i have setted every quit value (except quitOnEnd) to true.

[test.txt](https://github.com/marekdedic/imagelightbox/files/3456654/test.txt)

**Comment by marekdedic** [comment]
Hi,
Did you use the proper selector? From the file you've included it doesn't seem so... Take a look at the docs included in this repo to find out how to do it...
