### ISSUE TITLE
image load error handler

### ISSUE THREAD

**Issue by DaniSchenk** [marekdedic/imagelightbox#22]
hey! first, i really like your plugin, thank you for sharing...
i was wondering, if there is any error handling callback in your options.
i tried replacing the src element of the #imagelightbox by a default error image (with the onLoadStart option), but the img#imagelightbox element will not be created if the loading process of the image src fails, right?

i would like to replace the img src of the lightbox image by a default image, if the src cannot be loaded.

**Comment by rejas** [comment]
Hi Devbors, 
right now there is no errorcallback handling implemented, would be possible though by expanding the error function in line 214 with something. Is your js experience good enough to make that yourself (and send me a pullrequest) or wuld yu wait for me (or someone else) to add it?

**Comment by paxperscientiam** [comment]
@DevbrosDevelopment @rejas I'm looking into implementing Promise, which can be used for this.
