### ISSUE TITLE
Feature request: imagelightbox selector in overlay

### ISSUE THREAD

**Issue by paxperscientiam** [marekdedic/imagelightbox#223]
For scenarios where there are >1 ILB galleries, it would neat if the user could "jump" from gallery to gallery by clicking associated tabs when any given lightbox set is activated. Seamlessly and stuff.

**Comment by marekdedic** [comment]
Hi, I'm cleaning up old issues. This seems to me to be way too complicated and confusing for users. I'm closing this until there is a reasonable proposal with some mockups on how to do this with good UX.
