### ISSUE TITLE
Swipe doesn't work if quitOnImgClick is set

### ISSUE THREAD

**Issue by andreas-mausch** [marekdedic/imagelightbox#233]
Haven't tested it, but maybe just change the order of the `ifs` here?
https://github.com/marekdedic/imagelightbox/blob/d26fbd0db7c45fd1bb40f5b7654519d6461c938f/src/imagelightbox.js#L512

**Comment by marekdedic** [comment]
Hi,
thanks for the report. I am not sure whether changing the order would or would not then break quitOnClick on touch devices.... Will look into it

**Comment by marekdedic** [comment]
Hi, I think this should be fixed as of #930
