### ISSUE TITLE
Add swipe/slide/zoom functionality

### ISSUE THREAD

**Issue by rejas** [marekdedic/imagelightbox#36]
From "paxperscientiam": On the UX side of things, the ability to slide over to the next image via trackpad or mobile screen, would be great. To this end, I think we want a sliding motion to be equivalent to pressing left/right buttons, correct?"

Correct :-)

**Comment by paxperscientiam** [comment]
@rejas Just for the record, there is no interest in adding dependencies, correct?

**Comment by rejas** [comment]
No, only if it was very very small. For exmaple issue #47 would be really easy to fix if I would use hammer.js but then the size of the library doubles....

**Comment by paxperscientiam** [comment]
@rejas just to update, mobile finger sliding works just fine. It's only trackpad that does not.

**Comment by rejas** [comment]
Trackpads? Well, for those that want to add support for that, they could use their own library for detecting that an call a function for next / prev on our library. what do you think?

**Comment by ledeniz** [comment]
> 
> 
> @rejas just to update, mobile finger sliding works just fine. It's only trackpad that does not.

For me zooming doesn't work on Pixel XL with Android 9 and Chrome 86.0.4240.198

Do you have to configure it the right way to work? Or did you mean sliding next/prev and not zooming?

**Comment by marekdedic** [comment]
Swipe is currently working as intended, if there is anything wrong with zoom, please open a new issue with a clear description of why the current state is lacking.
