### ISSUE TITLE
Multiple gallery auto

### ISSUE THREAD

**Issue by vasilyman** [marekdedic/imagelightbox#91]
This is code for unlimited gallerys:

    var attrs = {};
    var classes = $("a[data-imagelightbox]").map(function(indx, element){  
      var key = $(element).attr("data-imagelightbox");
      attrs[key] = true;
      return attrs;
    });
    var attrsName = Object.keys(attrs);

    attrsName.forEach(function(entry) {
        $( "[data-imagelightbox='"+entry+"']" ).imageLightbox({
            overlay: true
        });
    });

it automatically searches attr's data-imagelightbox and sorting by separate albums! =)

**Comment by rejas** [comment]
Nice, would you make a pullrequest for that?

**Comment by vasilyman** [comment]
not sure I could do it at the moment. I just registered on GitHub and is not understood at this site. I am glad that someone this snippet will be useful.

**Comment by paxperscientiam** [comment]
Thank you for the contribution @vasilyman. Would you mind providing a minimally working example?

**Comment by vasilyman** [comment]
working example:
https://jsfiddle.net/7ow26fcg/

**Comment by marekdedic** [comment]
Multiple galleries were slightly reworked in 2.0, closing this for now
