### ISSUE TITLE
Remove dependency on jQuery

### ISSUE THREAD

**Issue by marekdedic** [marekdedic/imagelightbox#914]
It actually wouldn't be that hard to remove the dependency on jQuery. Given its falling usage, I think we should consider it.

I think we could still provide a small wrapper that keeps the current functionality intact...

**Comment by paxperscientiam** [comment]
Some messy thoughts from me:

There's a question of the target audience at play. jQuery is still very popular, even if flagging, and it provides an interface that's easy.

On the one hand, removing the dependency on jquery would mean leaner builds for end-users. On the other hand, jquery is really nice.

Some approaches come to mind:

- Remove jquery dependence, but still provide a way for jquery users to register ILB functions.
- Deprecate jquery in next major release ("A"), then removed in subsequent major release (B). 
  - Support patches for "A" for some period.

**Comment by marekdedic** [comment]
Hi,
thanks for the input, I was thinking along the lines of the first approach - probably add to the `dist` folder  files `imagelightbox.js` which doesn't require jQuery and `imagelightbox.jquery.js` which preserves the current interface as-is. That way current users can continue using imagelightbox as they were before, but can also choose to ditch jQuery and use the new interface.
